import '../model/book.dart';

class BookController {
  List<Book> fetchLatestBooks() {
    return [
      Book(
        bookid: 1,
        name: 'A Borrowed Path',
        image: 'assets/images/A Borrowed Path.jpg',
        author: 'Unknown',
        description: 'A journey of self-discovery and resilience.',
        price: 1800,
        category: 'Fiction',
        condition: 'Good',
        year: 2020,
        language: 'English',
        numberOfPages: 320,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 2,
        name: 'Beautiful Lies',
        image: 'assets/images/Beautiful Lies.jpg',
        author: 'Lisa Unger',
        description: 'A gripping psychological thriller full of twists.',
        price: 2200,
        category: 'Thriller',
        condition: 'New',
        year: 2021,
        language: 'English',
        numberOfPages: 400,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 3,
        name: 'Echo in Time',
        image: 'assets/images/Echo in time.jpg',
        author: 'Boo Walker',
        description:
            'A time travel romance that will have you on the edge of your seat!',
        price: 2000,
        category: 'Romance',
        condition: 'Fair',
        year: 2018,
        language: 'English',
        numberOfPages: 350,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 4,
        name: 'Echo of Old Book',
        image: 'assets/images/EchoofOldBook.jpg',
        author: 'Unknown',
        description: 'A story lost in the past, waiting to be rediscovered.',
        price: 1900,
        category: 'Mystery',
        condition: 'Poor',
        year: 2017,
        language: 'English',
        numberOfPages: 250,
        forWhat: 'Rent',
      ),
      Book(
        bookid: 5,
        name: 'Macbeth',
        image: 'assets/images/Macbeth.jpg',
        author: 'William Shakespeare',
        description: 'A classic tragedy of power, ambition, and fate.',
        price: 1500,
        category: 'Drama',
        condition: 'Good',
        year: 2015,
        language: 'English',
        numberOfPages: 180,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 6,
        name: 'Never Ending Sky',
        image: 'assets/images/Never ending sky.jpg',
        author: 'Unknown',
        description: 'An inspiring tale of endless possibilities.',
        price: 1700,
        category: 'Fiction',
        condition: 'Good',
        year: 2019,
        language: 'English',
        numberOfPages: 310,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 7,
        name: 'Romeo and Juliet',
        image: 'assets/images/Romeo Juliet.jpg',
        author: 'William Shakespeare',
        description: 'The timeless love story of star-crossed lovers.',
        price: 1600,
        category: 'Drama',
        condition: 'Good',
        year: 2015,
        language: 'English',
        numberOfPages: 210,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 8,
        name: 'Soul',
        image: 'assets/images/soul.jpg',
        author: 'Unknown',
        description: 'A deep dive into the essence of life and spirit.',
        price: 1800,
        category: 'Philosophy',
        condition: 'Fair',
        year: 2018,
        language: 'English',
        numberOfPages: 300,
        forWhat: 'Rent',
      ),
      Book(
        bookid: 9,
        name: 'Tempest',
        image: 'assets/images/Tempest.jpg',
        author: 'William Shakespeare',
        description: 'A dramatic tale of magic, betrayal, and revenge.',
        price: 1550,
        category: 'Drama',
        condition: 'Good',
        year: 2017,
        language: 'English',
        numberOfPages: 180,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 10,
        name: 'The Grammar',
        image: 'assets/images/The Grammar.png',
        author: 'Unknown',
        description: 'A comprehensive guide to mastering language.',
        price: 1400,
        category: 'Education',
        condition: 'New',
        year: 2020,
        language: 'English',
        numberOfPages: 150,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 11,
        name: 'The Half Known',
        image: 'assets/images/The half know.png',
        author: 'Unknown',
        description: 'A mystery novel filled with secrets and revelations.',
        price: 1750,
        category: 'Mystery',
        condition: 'Fair',
        year: 2019,
        language: 'English',
        numberOfPages: 340,
        forWhat: 'Rent',
      ),
      Book(
        bookid: 12,
        name: 'The House of Lost Secrets',
        image: 'assets/images/The House of Lost Secrets.jpg',
        author: 'Unknown',
        description: 'A thrilling adventure into the unknown.',
        price: 2100,
        category: 'Adventure',
        condition: 'Good',
        year: 2021,
        language: 'English',
        numberOfPages: 370,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 13,
        name: 'The Lean Startup',
        image: 'assets/images/The Lean Startup.png',
        author: 'Eric Ries',
        description: 'A revolutionary approach to business and innovation.',
        price: 2500,
        category: 'Business',
        condition: 'New',
        year: 2022,
        language: 'English',
        numberOfPages: 300,
        forWhat: 'Sell',
      ),
      Book(
        bookid: 14,
        name: 'The Naturalist',
        image: 'assets/images/The Naturalist.jpg',
        author: 'Andrew Mayne',
        description: 'A suspenseful thriller with a scientific twist.',
        price: 2300,
        category: 'Thriller',
        condition: 'New',
        year: 2020,
        language: 'English',
        numberOfPages: 290,
        forWhat: 'Sell',
      ),
    ];
  }

  List<Book> fetchExchangeBooks() {
    return [
      Book(
        bookid: 15,
        name: 'To Kill a Mockingbird',
        image: 'assets/images/To Kill a Mocking bird.png',
        author: 'Harper Lee',
        description: 'A dramatic tale of justice, race, and moral growth.',
        price: 1550,
        category: 'Fiction',
        condition: 'Good',
        year: 2019,
        language: 'English',
        numberOfPages: 281,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 10,
        name: 'The Grammar',
        image: 'assets/images/The Grammar.png',
        author: 'Unknown',
        description: 'A comprehensive guide to mastering language.',
        price: 1400,
        category: 'Education',
        condition: 'New',
        year: 2020,
        language: 'English',
        numberOfPages: 150,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 11,
        name: 'The Half Known',
        image: 'assets/images/The half know.png',
        author: 'Unknown',
        description: 'A mystery novel filled with secrets and revelations.',
        price: 1750,
        category: 'Mystery',
        condition: 'Fair',
        year: 2019,
        language: 'English',
        numberOfPages: 340,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 12,
        name: 'The House of Lost Secrets',
        image: 'assets/images/The House of Lost Secrets.jpg',
        author: 'Unknown',
        description: 'A thrilling adventure into the unknown.',
        price: 2100,
        category: 'Adventure',
        condition: 'Good',
        year: 2021,
        language: 'English',
        numberOfPages: 370,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 16,
        name: 'The Wide Wide Sea',
        image: 'assets/images/The wide wide sea.jpg',
        author: 'Eric Ries',
        description: 'An expansive tale about exploration and discovery.',
        price: 2500,
        category: 'Adventure',
        condition: 'Good',
        year: 2020,
        language: 'English',
        numberOfPages: 380,
        forWhat: 'Exchange',
      ),
      Book(
        bookid: 17,
        name: 'The Plan',
        image: 'assets/images/The Plan.png',
        author: 'Andrew Mayne',
        description: 'A suspenseful thriller with a scientific twist.',
        price: 2300,
        category: 'Thriller',
        condition: 'Fair',
        year: 2021,
        language: 'English',
        numberOfPages: 290,
        forWhat: 'Exchange',
      ),
    ];
  }
}
